### ISSUE TITLE
Error Save Password Required Bug

### ISSUE THREAD

**Issue by MetricCepheid** [kithywithy/Ruthenium#1]
I was screwing around making a Guest profile I got rid of the password from the `data.ruth` file I was able to log in I went into Management and I tried saving it without a password I pressed save, it said "Error Password Required" I then pressed cancel I logged out I went into an admin account and I went into Management, I pressed save and it did save, but it gave me the same error message as if the game thought I was still in the Guest account, but yet it still saved.

**Comment by KithM** [comment]
@Roystermeat This issue has been resolved for version 0.1.406 of Ruthenium. Thank you for your cooperation. If this issue persists, create a new issue and we will further resolve it then.
