### ISSUE TITLE
Things still open after Profile deleted

### ISSUE THREAD

**Issue by MetricCepheid** [kithywithy/Ruthenium#2]
I went back into the Guest account that I had made, and I decided to delete the account. I tried recreating the Guest account without the password box filled in it said "Password Required" I logged back in to the Admin account the Management box was still opened with the words "Password Required" still there with guest in the account name box and no password in the password box.

**Comment by KithM** [comment]
@Roystermeat This issue has been resolved for version 0.1.406 of Ruthenium. Thank you for your cooperation.
