### ISSUE TITLE
Permissions/Manage

### ISSUE THREAD

**Issue by MetricCepheid** [kithywithy/Ruthenium#4]
I was messing around with permissions I tried changing my password in the Management screen and it wouldn't let me so I went into Permission Management and I deleted `Settings.Manage.Self` I tried putting it back into Permissions and it added two of the `Settings.Manage.Self`. 

**EDIT**: I went ahead and deleted another one I put it back into the Permissions box and it added two.

**Comment by KithM** [comment]
Thank you for submitting this bug. The issue has already been resolved and will be updated ASAP in the next version.
