### ISSUE TITLE
Permissions reset after registering a new user

### ISSUE THREAD

**Issue by MetricCepheid** [kithywithy/Ruthenium#5]
Okay so, every time I register a new user I go back into my old user, I go into Manage Permissions and all of my old permissions reset and are gone. 

**EDIT**: It only goes to one specific person like when you logout register a new user and go back in to the first one it would be a possibility if you have multiple users that the Permissions don't disappear.

**Comment by KithM** [comment]
This issue will be temporarily closed as it is likely solved. If the issue reappears again the conversation will open back up and we will take a further look at it.

**Comment by KithM** [comment]
This issue has been resolved in the current version 1.0.408. If the issue still persists for some reason, however, it will be reopened. Thank you for your cooperation.
